#!/usr/bin/env bash
$JAVA_HOME/bin/java $JAVA_OPTIONS --add-opens java.base/java.util=ALL-UNNAMED \
    -XX:+TieredCompilation \
    -XX:TieredStopAtLevel=1 \
    -XX:+UseSerialGC \
    -jar function.jar "com.claranet.vies.proxy.Handler::handleRequest"